Mark Position now Queries Stages
mark_position within the BaseViewController now queries the stages first when the right-click mark position event is triggered. This called a command in the Controller which creates a thread in the model, and blocks the Controller from continuing until the thread is complete, ensuring that the new positions have been recorded.

camera_view has some more type hinting.

And I randomly received a ValueError when opening the software once on my computer. I might have been typing when it opened, which triggered the following error, which is now handled with another Exception clause:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/miniconda3/envs/navigate/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/Dean/Documents/GitHub/navigate/src/navigate/controller/sub_controllers/menus.py", line 281, in <lambda>
    lambda *args: self.stage_movement("w"),
  File "/Users/Dean/Documents/GitHub/navigate/src/navigate/controller/sub_controllers/menus.py", line 924, in stage_movement
    self.parent_controller.stage_controller.stage_key_press(self.fake_event)
  File "/Users/Dean/Documents/GitHub/navigate/src/navigate/controller/sub_controllers/stages.py", line 192, in stage_key_press
    self.up_btn_handler(axis="y", large_step=False)()
  File "/Users/Dean/Documents/GitHub/navigate/src/navigate/controller/sub_controllers/stages.py", line 438, in handler
    float(position_val.get())
ValueError: could not convert string to float: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/miniconda3/envs/navigate/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/Dean/Documents/GitHub/navigate/src/navigate/controller/sub_controllers/menus.py", line 295, in <lambda>
    lambda *args: self.stage_movement("a"),
  File "/Users/Dean/Documents/GitHub/navigate/src/navigate/controller/sub_controllers/menus.py", line 924, in stage_movement
    self.parent_controller.stage_controller.stage_key_press(self.fake_event)
  File "/Users/Dean/Documents/GitHub/navigate/src/navigate/controller/sub_controllers/stages.py", line 194, in stage_key_press
    self.down_btn_handler(axis="x", large_step=False)()
  File "/Users/Dean/Documents/GitHub/navigate/src/navigate/controller/sub_controllers/stages.py", line 487, in handler
    float(position_val.get())